package levelBuilder.move;

import javax.swing.undo.UndoableEdit;

import levelBuilder.entity.LevelBuilder;

public class RemoveMove extends Move{

	String newValue;
	int oldValue;
	UndoableEdit undo;
	
	/**
	 * Class Constructor
	 * @param newValue: the new string value of the field
	 * @param oldValue: the old string value of the field
	 * @param undo: the UndoableEdit object generated by the JTextFIeld's Document
	 */
	public RemoveMove(String newValue, int oldValue, UndoableEdit undo){
		this.newValue = newValue;
		this.oldValue = oldValue;
		this.undo = undo;
	}
	
	/**
	 * checks to see if the move is valid. If the move is valid doMove converts new value string into an appropriate integer. 
	 * Then updates the appropriate attribute in the LevelBuilder's level class.
	 * 
	 * @param editor: the LevelBuilder entity class
	 */
	@Override
	public boolean doMove(LevelBuilder editor) {
		if(valid(editor)){
			int newIntValue;
			if(newValue.matches("")){
				newIntValue = 0;
			}
			else{
				newIntValue = Integer.parseInt(newValue);
			}
						
			editor.getLevel().setNumRemove(newIntValue);
			return true;
			
		}
		else{
			return false;
		}
		
	}

	/**
	 * Undos the move by setting the appropriate attribute in the LeveBuilder level to oldValue and then undoing the change to the corresponding text field.
	 * @param editor: top level level builder entity object.
	 */
	@Override
	public boolean undo(LevelBuilder editor) {
		
		editor.getLevel().setNumRemove(oldValue);
		undo.undo();	
		
		return true;
	}

	/**
	 * Determines if a move is valid by checking to see if the newValue contains only numerals and the empty string
	 * @param editor: top level level builder entity object.
	 */
	@Override
	public boolean valid(LevelBuilder editor) {
		return newValue.matches("[0-9]+") || newValue.matches("");
	}  

}
